### ISSUE TITLE
Add option for tsv file location

### ISSUE THREAD

**Issue by KarelBerka** [MPI-Dortmund/pymissense#4]
Would it be possible to add option to point to alpha.tsv file to skip its download?

**Comment by thorstenwagner** [comment]
Sure! I will add this option tomorrow :-)

28.09.2023 22:53:50 Karel Berka ***@***.***>:

**Comment by phpeters** [comment]
Great! I'm also looking forward to this, because I got a ssl.SSLCertVerificationError. 
Thanks a lot!
Philipp
