### ISSUE TITLE
add a row of average value to PDF 

### ISSUE THREAD

**Issue by KarelBerka** [MPI-Dortmund/pymissense#7]
since you already calculate them for PDB file, it might be a good addition.

**Comment by thorstenwagner** [comment]
Sure! I will be in vacation until 11 october, but then I gonna implement it.

**Comment by thorstenwagner** [comment]
Did you had something like this in mind?

![image](https://github.com/MPI-Dortmund/pymissense/assets/1113977/b636bd85-7b56-48ba-9e6e-4c49d310f46e)

**Comment by thorstenwagner** [comment]
Ok, here is the final modified plot:

![image](https://github.com/MPI-Dortmund/pymissense/assets/1113977/0f18890b-edb5-4468-bdc7-4ac5f22e3f17)

I gonna make a PR now.
